language: node_js
node_js:
  - "10"
dist: trusty
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm i -g @angular/cli@7.0.5
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm rebuild node-sass
  - npm ci

script:
  - npm run lint
  - npm run test
  - npm run build
