
language: node_js
node_js:
  - '10'
sudo: required
dist: trusty
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm i -g @angular/cli@7.0.5
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm ci

script:
  npm run lint
script:
  npm run test
script:
  npm run build

